//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaneSystems.Arkane.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkaneSystems.Arkane.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkane Systems.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright ⓒ 2016-2026 Arkane Systems / Alistair J. R. Young.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be a method with unassigned generic type parameters..
        /// </summary>
        internal static string DisposerByReflection_DisposerByReflection_CantBeMethodWithUnassignedGenericTypeParams {
            get {
                return ResourceManager.GetString("DisposerByReflection_DisposerByReflection_CantBeMethodWithUnassignedGenericTypePa" +
                        "rams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be a static method..
        /// </summary>
        internal static string DisposerByReflection_DisposerByReflection_CantBeStaticMethod {
            get {
                return ResourceManager.GetString("DisposerByReflection_DisposerByReflection_CantBeStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a parameterless method..
        /// </summary>
        internal static string DisposerByReflection_DisposerByReflection_MustBeParameterlessMethod {
            get {
                return ResourceManager.GetString("DisposerByReflection_DisposerByReflection_MustBeParameterlessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object does not have a public parameter instance method {0}..
        /// </summary>
        internal static string DisposerByReflection_GetPublicParameterlessInstanceMethod_ObjectDoesNotHaveAPublicParameterInstanceMethod {
            get {
                return ResourceManager.GetString("DisposerByReflection_GetPublicParameterlessInstanceMethod_ObjectDoesNotHaveAPubli" +
                        "cParameterInstanceMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be divisible by {0}, but was {1}..
        /// </summary>
        internal static string DivisibleByAttribute_Validate_ValueMustBeDivisibleBy {
            get {
                return ResourceManager.GetString("DivisibleByAttribute_Validate_ValueMustBeDivisibleBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality must be implemented by a subclass of this base class..
        /// </summary>
        internal static string SubclassResponsibilityException_SubclassResponsibilityException_DefaultMessage {
            get {
                return ResourceManager.GetString("SubclassResponsibilityException_SubclassResponsibilityException_DefaultMessage", resourceCulture);
            }
        }
    }
}
